export * from "./class"
export * from "./course"
export * from "./student"
export * from "./staff"
export * from "./faculty"
export * from "./activities"
export * from "./submissions"
export * from "./demand"